name: etiya_assignment
description: Etiya Assignment Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  mocktail: ^0.2.0
  logging: ^1.0.2
  flutter_bloc: ^8.0.1
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  lazy_load_scrollview: ^1.3.0
  cached_network_image: ^3.2.1
  auto_route: ^4.2.1
  bloc_test: ^9.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.3.0
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0


flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700